name: frontend deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "csport" #Must be unique in Heroku
          heroku_email: "quangvn2508@gmail.com"
          appdir: "frontend" # <- This will point to the api folder in your project
